docs/conf.py
invenio_records_lom/cli.py
invenio_records_lom/ext.py
invenio_records_lom/fixtures/demo.py
invenio_records_lom/oai.py
invenio_records_lom/records/__init__.py
invenio_records_lom/records/api.py
invenio_records_lom/records/systemfields/__init__.py
invenio_records_lom/records/systemfields/results.py
invenio_records_lom/resources/resources.py
invenio_records_lom/resources/serializers/__init__.py
invenio_records_lom/resources/serializers/schemas.py
invenio_records_lom/services/components.py
invenio_records_lom/services/services.py
invenio_records_lom/ui/records/errors.py
invenio_records_lom/ui/records/records.py
setup.cfg
tests/conftest.py
tests/test_cli.py
tests/test_invenio_records_lom.py
tests/test_pids_service.py
tests/test_service.py

use pylint from now on
includes various fixes suggested by pylint
notes:
- added `UISchema.is_draft` to forgo private access
- renamed argument-names to fit conventional names
- pylint won't find `lxml.Elementmaker` because it's a C-module
- changed method-signature to conform with parent-class's
- shortened names to keep within character-per-line limit

add pylint

---

docs/conf.py

- language = None in Sphinx 5.0.0 should be set to "en"
- use datetime to set the current year in the documentation

fix combined fixes

---

invenio_records_lom/ext.py
invenio_records_lom/fixtures/demo.py
invenio_records_lom/services/services.py
invenio_records_lom/utils/util.py
tests/test_service.py

- `service.create` now automatically adds repo-pid to metadata
- use the recommended importlib.resources for importing files
- use standardlib's `csv.reader` to read csv
- rename and rewrite `DotAccessWrapper.check` for clarity
- `LOMMetadata` now operates on jsons like the ones in the database
(used to operate only on the `metadata`-attribute)
- `LOMMetadata.__init__` only wraps input (unchanged)
- `LOMMetadata.create` creates an object given its parameters (new)
- `LOMMetadata.append_*`-methods now don't duplicate data
(this makes those methods idempotent)
- added `LOMMetadata.append_relation`

improve metadata-creation

---

invenio_records_lom/config.py
invenio_records_lom/fixtures/demo.py
invenio_records_lom/resources/config.py
invenio_records_lom/resources/resources.py
invenio_records_lom/resources/serializers/schemas.py
invenio_records_lom/services/config.py
invenio_records_lom/services/permissions.py
invenio_records_lom/services/pids.py
invenio_records_lom/services/schemas/metadata.py
invenio_records_lom/services/services.py
invenio_records_lom/ui/records/deposits.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/debug.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js
setup.cfg
tests/test_cli.py

new features:
- `Delete`-Button on deposit-page now works
- publishing now works
- new DOI-field to generate a DOI for the upload
- includes some minor updates to upload-page as per last LLT-meeting
- includes `invenio-app-rdm` v11 compatibilty
fixes:
- update LOMToDatacite44Schema (this was missed when updating metadata-schema to conform with LOM-UIBK)
- service.create doesn't use `draft_item.to_dict()` anymore due to its many side effects
- fxed a couple of javascript-warnings
notes:
- invenio's DOI-field also allows to use a previously existing DOI, not sure whether we have that use-case but I left it in for now
- some errors are shown twice as of right now, this is better fixed by the `deeper-error-levels`-PR on `react-invenio-deposit` (once I get to finish that...)

support DOI, publishing, deleting

---

invenio_records_lom/ext.py
invenio_records_lom/resources/__init__.py
invenio_records_lom/resources/config.py
invenio_records_lom/services/config.py
invenio_records_lom/views.py
setup.cfg

different file extensions call different previewers
image-preview requires:
-  images to have associated preview-hyperlinks
- an IIIF-resource configured to link those hyperlinks to a service
- a service configured to look up files in lom-SQL-tables (instead of rdm-SQL-tables)

fix image-preview by implementing iiif-resource

---

invenio_records_lom/templates/invenio_records_lom/record.html
invenio_records_lom/templates/invenio_records_lom/records/files.html
invenio_records_lom/templates/invenio_records_lom/records/macros/files.html
invenio_records_lom/ui/records/records.py

- fix broken accordions for file-preview/file-list
- use `section` html-elements instead of `div` where applicable
- add missing "Files"-header
- bring `record_export` up to date with `invenio_app_rdm`'s export

update landing page

---

invenio_records_lom/cli.py
invenio_records_lom/jsonschemas/lomrecords/lom-v1.0.0.json
invenio_records_lom/jsonschemas/lomrecords/records/record-v1.0.0.json
invenio_records_lom/records/api.py
invenio_records_lom/upgrade_scripts/__init__.py
invenio_records_lom/upgrade_scripts/migrate_0_8_to_0_9.py
tests/conftest.py

this key serves multiple purposes for the corresponding record:
- gives path to opensearch-mapping relative to its entrypoint
- gives path to jsonschema relative to its entrypoint
- allows to derive name of corresponding index
the last point is needed by OAI-PMH, but the others need be kept in line
verification of jsons is now done by marshmallow, hence the jsonschemas are just dummies
migration-scripts are located in `invenio_records_lom/upgrade_scripts`
to upgrade, run
`$ pipenv run invenio shell /path/to/migrate_0_8_to_0_9.py`
`$ invenio lom reindex`

add "$schema"-key to jsons in database

---

invenio_records_lom/resources/serializers/schemas/oai.py
invenio_records_lom/services/schemas/metadata.py
invenio_records_lom/ui/records/deposits.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js

also fills in publisher from config's `LOM_PUBLISHER` for new uploads
`metadata.technical.format` holds the MIME-type
for compatibility with older records,
- is of type `list[str]`
- but newly created records must have length of list ==1
`services/schemas/metadata.py` holds schemas that check record-data from incoming API-calls made by upload-page
errors thrown by these schemas are shown to the uploading user

add `format` and `resource-type` to upload-page

---

invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js

cleanups:
- remove unused imports
- remove TODO-comments that have already been done
- remove old React-components left over from initial exploration
- make `DropdownField`s for optional metadata clearable
- add `htmlFor` to all `<label>`s
- convert to function-based React-components as per [React recommendation](https://react.dev/reference/react/Component)
- differentiate inner and outer `Dropdown`s to prevent duplicate nesting
- add some comments for clarity
- clean up serialization
note:
cleanup ain't finished, I left some TODO-comments for future cleanups

clean up various upload-page related things

---

invenio_records_lom/services/facets.py

* the problem is, that there could be license urls with a trailing slash
and it is a little bit cumbersome to add all possible cases to the
mapping

fix: license facets trailing slash

---

invenio_records_lom/services/facets.py
invenio_records_lom/ui/records/deposits.py

* the last character of a license url should be the slash. the url
should close with a slash if there is no parameter value at the
end.

fix: licenses url with slash as last character

---

LICENSE
babel.ini
docs/license.rst
invenio_records_lom/services/facets.py
invenio_records_lom/services/schemas/metadata.py
invenio_records_lom/templates/invenio_records_lom/base.html
invenio_records_lom/templates/invenio_records_lom/not_licensed_text.html
invenio_records_lom/templates/invenio_records_lom/records/macros/files.html
invenio_records_lom/templates/invenio_records_lom/records/macros/tree.html
invenio_records_lom/templates/invenio_records_lom/search.html
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/debug.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/LOMRecordManagement.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/components.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/less/invenio_records_lom/theme.less
invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/i18next-scanner.config.js
invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/i18next.js
invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/messages/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/scripts/compileCatalog.js
invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/scripts/initCatalog.js
invenio_records_lom/ui/theme/webpack.py
run-tests.sh

some file-headers erroneously claimed the file to be part of a package other than `invenio-records-lom`
- fix that
- normalize file headers as to make them look the same
- fix some other issues with file headers

clean up file headers

---

invenio_records_lom/utils/metadata.py
invenio_records_lom/utils/util.py

facets consider http-URLs different from https-URLs
this standardizes rights-urls when `LOMMetadata` is used to build data

standardize rights-URLs passed to `LOMMetadata`

---

invenio_records_lom/services/schemas/metadata.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js
invenio_records_lom/utils/util.py

When uploading via upload-page, the entered data will be validated by the backend.
If there are any `ValidationError`s, the corresponding error-message(s) will be shown to users of the upload-page.
These error-messages are not (yet) translated.
This PR marks those error-messages for translation.
Other error-messages shouldn't be visible to users.
Those haven't been marked for translation, but have been reworded.
Includes a commit to replace the deprecated function `importlib.resources.open_text`.
See [here](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.open_text) for official documentation on what to replace it with.

mark user-visible errors for translation

---

invenio_records_lom/ui/theme/webpack.py

* the dependency was missing, because it was added previously by other
packages, but it has been removed from there so it has to be added
here now.

deps: add missing dependency

---

invenio_records_lom/services/components.py
invenio_records_lom/services/services.py
invenio_records_lom/utils/__init__.py
invenio_records_lom/utils/metadata.py
invenio_records_lom/utils/util.py
setup.cfg
tests/test_service.py

- services: move add identifier to components
- utils: add create_record function
- utils: add LOMRecordData class

add create record function

---

invenio_records_lom/resources/config.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js

follows an upstream-change from `invenio-rdm-records`: [#1649](https://github.com/inveniosoftware/invenio-rdm-records/pull/1649)
after the upstream change, upload-page API-calls accepts only `vnd.inveniordm.v1+json` as mime-type
but
- our upload-page uses their javascript and hence now requires `vnd.inveniordm.v1+json` as mime-type
- our backend does not provide that mime-type
this breaks a bunch of functionality of the upload-page, including file-upload
this PR fixes this by content-negotiating our custom mime-type (`application/vnd.inveniolom.v1+json`)

update: negotiate custom mimetype

---

invenio_records_lom/services/schemas/metadata.py

the signature of our custom `marshmallow`-Field got changed by mistake when we updated from `pylint` to `ruff`

fix: re-align function signature with marshmallow

---

invenio_records_lom/resources/config.py

`flask_resources.parser.RequestParser.__init__` requires either:
- an instance of `dict`
- a marshmallow schema
`MappingProxyType` is neither, making `RequestParser` mis-initialize
see [`RequestParser.__init__`](https://github.com/inveniosoftware/flask-resources/blob/master/flask_resources/parsers/base.py#L101)

fix: use `dict` for `RequestParser` args

---

invenio_records_lom/ui/records/records.py

invenio now passes new arguments to `record_file_preview` functions (theirs as well as ours)
this PR changes the signature of our `record_file_preview` function to accommodate that
(I couldn't find the exact commit of theirs that changed this, but it must be within the last month or so)

fix: realign signature of file-preview view-function

---

invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/components/EditButton.js

I missed this in the recent update to content-negotiation (i.e. negotiate our custom mime-type over `application/json`)
for some reason, `EditButton` uses Javascript's `post` method directly
(most other code uses `axios` configured with data passed to frontend instead)
this fixes clicking the following button:
the user-dashboard has a submenu *Educational Resources*
this submenu shows a list of the user's OER-uploads
those OER-upload entries show a button `Edit` in their upper-right corner
also see [this commit](https://github.com/inveniosoftware/invenio-app-rdm/commit/d4f58d3e92a78f2f94eb5998195ede19d69f4f5c) for `invenio-app-rdm`, where they change their `EditButton`'s requested mime-type

fix: request our custom mime-type in `EditButton`

---

invenio_records_lom/ui/records/deposits.py
invenio_records_lom/utils/metadata.py

`create` method creates a *record*, not just *metadata*
thus it should be a method of `LOMRecordData`, not of `LOMMetadata`
`deposit_create` wrongly created metadata rather than a full record
this means that initial values for a new upload were broken
(in particular, publisher had no default filled in...)

fix: create full record rather than just metadata

---

invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/index.js

for react>=18, `ReactDom.render` was deprecated in favor of `createRoot`
see:
- react changelog on github: [this line](https://github.com/facebook/react/blob/main/CHANGELOG.md?plain=1#L96)
- react 18 upgrade guide: [this section](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)

update: update deprecated `ReactDOM.render`

---

invenio_records_lom/records/systemfields/relations.py
invenio_records_lom/records/systemfields/results.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/index.js

* This reverts commit 779a9674bbc1c1affbea37515a3fa5fc2f872b04.
* reason: the change is for react >= 18 and we are not yet there to
upgrade

Revert: update deprecated `ReactDOM.render`

---

invenio_records_lom/ui/records/records.py

in particular, `filename` was passed as a kwarg,
but `record_file_download` took no such keyword argument...

fix: accept extra kwargs on file-download

---

invenio_records_lom/services/tasks.py

either would have worked:
- `datetime.UTC` (`datetime` with upper-case `.UTC`)
- `timezone.utc` (`timezone` with lower-case `.utc`)
but we got our wires crossed and used `timezone.UTC`
this bug was introduced when moving to ruff
relevant ruff error: [DTZ005](https://docs.astral.sh/ruff/rules/call-datetime-now-without-tzinfo/)

fix: get `UTC` timezone via correct attribute-name

---

invenio_records_lom/resources/serializers/ui/schema.py

records could be uploaded with external DOIs
in that case, they needn't have DATACITE_PREFIX as prefix
correct way is to get DOI from `"pids"` dict

fix: DOI resolution

---

invenio_records_lom/resources/serializers/oai/schema.py
invenio_records_lom/services/schemas/metadata.py

`OAISchema` is only used in serialization to `.dump` database-schemaed json to OAI-schemaed json
originally, `OAISchema` incorrectly used `.load` instead of `.dump`
this got changed in [this commit](https://github.com/tu-graz-library/invenio-records-lom/commit/7b421f1f4f83a910e71edb1365ee02de485938a7#diff-13b72c55af5f06511907a95e71621aaf5c0597ecfad90fda92a999acac0794f2R49)
when moving from `.load` to `.dump`, the commit *should also have* exchanged the incorrect `@pre_load` for `@pre_dump`, but didn't
due to issues with timezone-awareness, datetimes are timezone-unaware for now
see [here](https://github.com/inveniosoftware/invenio-oauthclient/pull/328#discussion_r1599993184) for discussion on this

various changes to OAI-PMH output for compatibility

---

invenio_records_lom/ui/records/records.py

DOI-URL for OER-records is of form `<domain>/oer/doi/<INSTITUTION-CODE>/<pid>` (e.g. `my-repo.org/oer/doi/10.1234/asdfg-hjk42`)
this then gets redirected to the landing-page's URL (e.g. `my-repo.org/oer/asdfg-hjk42`)
the actual redirect is done by the view-function `record_from_pid`
this function was passed additional kwargs (which it didn't accept), causing the attempted redirect to fail
this follows a similar upstream-change: [here](https://github.com/inveniosoftware/invenio-app-rdm/pull/2310)
apparently the redirected-to URL might change at some point
HTTP 301 *Moved Permanently* would have browsers cache the redirect forever
should the redirected-to URL change, this would result in a 404 for users...
`pass_*` decorators pass on all their received kwargs as later `pass_*` decorators …

Fix DOI-redirect by ignoring extraneous parameters

---

invenio_records_lom/fixtures/demo.py
invenio_records_lom/resources/serializers/oai/schema.py
invenio_records_lom/services/schemas/metadata.py
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js
invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js
invenio_records_lom/upgrade_scripts/migrate_0_17_to_0_18.py
invenio_records_lom/utils/metadata.py

A `learningresourcetype` is a value from [`https://w3id.org/kim/hcrt/scheme`](https://w3id.org/kim/hcrt/scheme).
e.g. `https://w3id.org/kim/hcrt/course` for courses
`LOMMetadata.append_learningresourcetype` takes a `str` which determines the `learningresourcetype` to add.
Currently, it only takes the last part of a `learningresourcetype` URL.
e.g. only `course`, not the full URL `https://w3id.org/kim/hcrt/course`
However, the full URL is often available when building metadata.
So this PR makes `LOMMetadata.append_learningresourcetype` accept the full URL `https://w3id.org/kim/hcrt/course` as its argument (just passing `course` still works too).
`LOMMetadata.append_learningresourcetype` creates `metadata.educational.learningresourcetype` as a list-of-objects.
In other places, …

Update handling of `metadata.educational.learningresourcetype`

---

invenio_records_lom/__init__.py
invenio_records_lom/fixtures/__init__.py
invenio_records_lom/records/systemfields/__init__.py
invenio_records_lom/services/__init__.py
invenio_records_lom/utils/__init__.py
invenio_records_lom/utils/util.py
pyproject.toml

fixes issues found by `ruff`'s new version 0.8.0:
- these rules have been removed from ruff and need no longer be ignored: `ANN101`, `ANN102`
- sort contents of `__all__` (as per now stabilized rule `RUF022`)
- use `collections.abc.Iterable` for type-annotations (rather than `typing.Iterable`)
links:
- release notes of `ruff` 0.8.0: [here](https://github.com/astral-sh/ruff/releases/tag/0.8.0)

fix: fix quibbles from ruff 0.8.0
