tu-graz-library/invenio-records-lom

docs/conf.py, invenio_records_lom/__init__.py, invenio_records_lom/api.py, invenio_records_lom/config.py, invenio_records_lom/ext.py, invenio_records_lom/fetchers.py, invenio_records_lom/loaders/__init__.py, invenio_records_lom/marshmallow/__init__.py, invenio_records_lom/marshmallow/json.py, invenio_records_lom/minters.py, invenio_records_lom/providers.py, invenio_records_lom/serializers/__init__.py, invenio_records_lom/version.py, invenio_records_lom/views.py, setup.py, tests/api/conftest.py, tests/conftest.py, tests/test_invenio_records_lom.py
=> moved the code base to be formated by black

.gitignore, invenio_records_lom/cli.py, invenio_records_lom/fixtures/__init__.py, invenio_records_lom/fixtures/demo.py, setup.py
create default 100 fake records
=> add demo cli

invenio_records_lom/services/permissions.py, invenio_records_lom/services/schemas/fields.py, setup.py
make invenio_records_lom compatible with invenio v7
=> V7 compatibility

.github/workflows/tests.yml, invenio_records_lom/config.py, invenio_records_lom/ext.py, invenio_records_lom/fixtures/__init__.py, invenio_records_lom/fixtures/demo.py, invenio_records_lom/records/api.py, invenio_records_lom/resources/serializers/__init__.py, invenio_records_lom/resources/serializers/schemas.py, invenio_records_lom/services/components.py, invenio_records_lom/services/config.py, invenio_records_lom/services/schemas/records.py, invenio_records_lom/services/services.py, invenio_records_lom/services/tasks.py, invenio_records_lom/ui/records/__init__.py, invenio_records_lom/ui/records/decorators.py, invenio_records_lom/ui/records/records.py, setup.py, tests/conftest.py, tests/test_pids_service.py, tests/test_service.py
=> implement DOI creation, add DOI tests

invenio_records_lom/records/systemfields/relations.py, invenio_records_lom/records/systemfields/results.py, invenio_records_lom/resources/serializers/__init__.py, invenio_records_lom/resources/serializers/schemas.py, invenio_records_lom/templates/invenio_records_lom/record.html, invenio_records_lom/ui/records/records.py
- use updated base-classes for serializers and schemas
- use `OneOfSchema` to serialize files/units/courses differently
- update landing page template
- show landing page also for drafts, *if* they are valid
- prettify HTML-output
- fix relations
=> update UI-serialization and landing page

MANIFEST.in, invenio_records_lom/config.py, invenio_records_lom/resources/config.py, invenio_records_lom/resources/resources.py, invenio_records_lom/resources/serializers/schemas.py, invenio_records_lom/templates/invenio_records_lom/base.html, invenio_records_lom/templates/invenio_records_lom/search.html, invenio_records_lom/ui/__init__.py, invenio_records_lom/ui/theme/__init__.py, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/components.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/less/invenio_records_lom/theme.less, invenio_records_lom/ui/theme/config.py, invenio_records_lom/ui/theme/views.py, invenio_records_lom/ui/theme/webpack.py, setup.cfg
- add the search feature
- fix missing schema for type link
=> add search v2

invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/debug.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js
=> Add .js-files that were erroneously missing from last PR

invenio_records_lom/templates/invenio_records_lom/not_licensed_text.html, invenio_records_lom/templates/invenio_records_lom/search.html, invenio_records_lom/translations/de/LC_MESSAGES/messages.po, invenio_records_lom/translations/messages.pot, invenio_records_lom/ui/records/decorators.py, invenio_records_lom/ui/records/deposits.py
* to upload oer it is necesary to have a license. it is not fully
implemented. for now 0 users have this license so none is allowed to
upload oer's
=> upload: require license permission

invenio_records_lom/config.py, invenio_records_lom/services/config.py, invenio_records_lom/services/facets.py, invenio_records_lom/templates/invenio_records_lom/search.html, invenio_records_lom/ui/theme/config.py, setup.cfg
- enable search-filtering by adding `.search` to service-config
- add "License" facet and configure for it to be used
=> implement and configure facets (=search-filters)

invenio_records_lom/resources/serializers/schemas/datacite.py, invenio_records_lom/resources/serializers/schemas/oai.py, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js, invenio_records_lom/utils/metadata.py
- stop grouping for data from upload-page
- stop grouping for data built with LOMMetadata
- group on OAI-PMH output computation to retain compatibility
=> stop grouping `lifecycle.contribute`s by role

invenio_records_lom/translations/de/LC_MESSAGES/messages.po, invenio_records_lom/translations/messages.pot, invenio_records_lom/ui/records/__init__.py, invenio_records_lom/views.py, setup.cfg
- wording: change
- metadata: remove metadata prefix
=> fix v12 inconsistencies

invenio_records_lom/services/config.py
* otherwise the queue of rdm was used
=> fix: indexer needs queue name

invenio_records_lom/resources/serializers/oai/serializer.py
* the method build_langstring should return a valid value
=> fix: method returns valid value

invenio_records_lom/resources/serializers/oai/schema.py, invenio_records_lom/services/schemas/metadata.py, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js, invenio_records_lom/utils/metadata.py
Data that users put into the upload-page was barely sanitized.
This PR adds sanitization.
=> sanitize data coming from upload-page

invenio_records_lom/services/permissions/policy.py
`inveniosoftware` has added new fields to permission policies since `LOMPermissionPolicy` was last changed.
This PR configures those newly added fields.
=> configure permissions newly added to invenio

invenio_records_lom/resources/serializers/oai/schema.py, invenio_records_lom/utils/vcard.py
- fix: vcard creation
- oai: add date to contribute
=> fix oai pmh authors v2

invenio_records_lom/config.py, invenio_records_lom/fixtures/demo.py, invenio_records_lom/resources/serializers/oai/schema.py, invenio_records_lom/services/permissions/policy.py, invenio_records_lom/services/services.py, invenio_records_lom/utils/__init__.py, invenio_records_lom/utils/metadata.py, invenio_records_lom/utils/util.py, tests/test_service.py
- utils: add check for duplicate
- metadata: fix selectors
=> improve metadata api

invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js, invenio_records_lom/ui/theme/webpack.py
This pull request addresses the issue of a deprecated dependency in the React application by removing it and replacing it with RDM for enhanced compatibility and functionality.
Identified and removed the deprecated dependency from the project.
Integrated RDM into the project structure to manage React dependencies efficiently.
Updated project configurations and dependencies to ensure seamless integration with RDM.
Tested the application thoroughly to verify compatibility and functionality with the new setup.
Manually tested the application after removing the deprecated dependency and integrating RDM.
Verified that all existing features continue to function as expected.
Checked for any potential regressions or compatibility issues with other parts of the application.
This pull request aims …
=> Remove deprecated dependency and use RDM for improved compatibility

invenio_records_lom/oai.py, invenio_records_lom/resources/serializers/oai/serializer.py
* the doi creation is optional and depends on the variable
DATACITE_ENABLED
=> oai: fix doi not exists

.eslintrc.yml, .github/workflows/tests.yml, .prettierrc, MANIFEST.in, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/components/EditButton.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/LOMDepositForm.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/components.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/debug.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/fields.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/deposit/serializers.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/LOMRecordManagement.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/components.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/search/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/user_dashboard/index.js, invenio_records_lom/ui/theme/assets/semantic-ui/translations/invenio_records_lom/i18next.js, run-js-linter.sh
to install `eslint` locally:
1. install it with the provided shell-script:
```sh
./run-js-linter.sh --install
```
2. this will use `npm install` to install necessary `npm` packages to the nearest `node_modules` folder
to run `eslint` locally:
1. run it with the provided shell-script
```sh
./run-js-linter.sh
```
`error` in `LOMRecordResultsListItem` was unused before this
now when clicking the `EditButton` fails, an error will be shown like this:
=> add eslint, fix problems eslint found

invenio_records_lom/config.py, invenio_records_lom/resources/config.py, invenio_records_lom/resources/resources.py, invenio_records_lom/resources/serializers/__init__.py, invenio_records_lom/resources/serializers/csl/__init__.py, invenio_records_lom/resources/serializers/csl/schema.py, invenio_records_lom/resources/serializers/csl/serializer.py, invenio_records_lom/templates/invenio_records_lom/record.html, invenio_records_lom/ui/theme/assets/semantic-ui/js/invenio_records_lom/landing_page/index.js
NOTE: this does not yet parse *name*s into *family-name*+*given-names*, but instead treats it as one unsplitable string
preview:
=> add basic citation-generation

invenio_records_lom/templates/invenio_records_lom/record.html, invenio_records_lom/ui/records/records.py
* there where changes in app-rdm about the usage of record vs record_ui,
one is the serialized object the other not
=> fix: record vs record_ui
